# 服务配置
server:
  # 端口
  port: 8080
  servlet:
    # 应用访问路径
    context-path: /geshanzsq-blog-admin-api
  tomcat:
    # tomcat uri 编码配置
    uri-encoding: UTF-8

# spring 配置
spring:
  profiles:
    active: dev
  # 资源信息
  messages:
    # 国际化资源配置文件路径
    basename: i18n/message
    encoding: utf-8
  application:
    name: geshanzsq-blog-admin-service
  servlet:
    multipart:
      # 文件上传最大大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# MyBatis Plus 配置
mybatis-plus:
  global-config:
    db-config:
      # 配置逻辑删除
      logic-delete-value: 2
      logic-not-delete-value: 1
      # 逻辑删除字段
      logic-delete-field: delFlag
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

# token 令牌配置
token:
  # 自定义令牌标识
  header: Authorization
  # 令牌有效期，默认 36000 秒，10 小时
  expire-time: 36000
  # 令牌参数
  token-param: token
  # 令牌前缀
  token-prefix: Bearer
  # 存入 redis 前缀
  token-redis-prefix: "token:admin:"
  # 刷新权限 redis 前缀
  permission-refresh-redis-prefix: "permission:refresh:admin:"

# 分页配置
page:
  # 默认分页记录数
  default-page-size: 10
  # 最大分页记录数
  max-page-size: 200

# 文件上传配置
file-upload:
  # 文件名称最大长度
  name-max-length: 200
  # 文件映射前缀
  map-prefix: /profile

# 接口文档配置
swagger:
  title: 格姗知识圈博客管理后台接口文档
  description: 包含用户管理、菜单管理、角色管理、数据字典、API 管理、参数配置、登录日志、操作日志、文章管理、分类管理、标签管理、友情链接、评论管理、第三方登录配置等功能
  author: geshanzsq
  url: http://geshanzsq.com
  email: 497301391@qq.com
  version: 1.0.0

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /blog/article/,/blog/about/edit
  # 匹配链接
  urlPatterns: /system/*,/blog/*

# 安全配置
security:
  # 不用登录就能访问
  not-login-urls:
    - /login
    - /getCaptchaImage
    - /bing/getBingImage